spring:
  application:
    name: ERMSuit
  datasource:
    # Using H2 for development, switch to PostgreSQL for production
    url: jdbc:h2:mem:ermsuit
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# JWT Configuration
app:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expiration-ms: 86400000  # 24 hours

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.ermsuit: DEBUG
    org.springframework.security: INFO

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

# Report Configuration
ermsuit:
  reports:
    output-dir: ./reports
    templates-dir: ./templates
